### ISSUE TITLE
Report several bugs

### ISSUE THREAD

**Issue by tansongchen** [blaulan/alfred-beancount#1]
Firstly, the script in Alfred needs to be modified, because currently a full path to python2 is specified:

![image](https://user-images.githubusercontent.com/31927845/75087005-dddcef80-5575-11ea-86b0-0ae36d35e961.png)

Secondly, there is an inconsistency for the file names:

![image](https://user-images.githubusercontent.com/31927845/75087064-bb97a180-5576-11ea-9b76-82d48383b94e.png)

Nevertheless it is a very good method for quick note of transactions.

**Comment by blaulan** [comment]
提到的几个问题已经在最新的 release 里修复了，同时也把参数从配置文件移到了 Alfred 的环境变量里，欢迎测试，如果有什么别的问题也随时联系。
